FROM python:3.13-slim

WORKDIR /project

# Копируем файл зависимостей
COPY requirements.txt /project/

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект в контейнер
COPY . /project

EXPOSE 8000
RUN mkdir -p /project/keys
RUN python -m core.gen_rsa_keys
CMD ["bash", "-c", "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"]
