"""empty message

Revision ID: fd290cf753c7
Revises: 1f4baf5a2a99
Create Date: 2025-10-11 19:58:34.701953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd290cf753c7'
down_revision: Union[str, Sequence[str], None] = '1f4baf5a2a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentality_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mentality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentality_calendar_id'), 'mentality_calendar', ['id'], unique=False)
    op.alter_column('images', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('worker_schedule_exceptions', 'is_day_off',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker_schedule_exceptions', 'is_day_off',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('images', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_mentality_calendar_id'), table_name='mentality_calendar')
    op.drop_table('mentality_calendar')
    # ### end Alembic commands ###
